coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch: off

comment: false

ignore:
  - "**/target/**"
  - "**/generated/**"
  - "**/generated-sources/**"

flags:
  samples:
    paths:
      - "samples/"