coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch: off

comment: false

ignore:
  - "**/target/**"
  - "**/generated/**"
  - "**/generated-sources/**"
  - "samples/**/customer-service-consumer/**"

flags:
  samples:
    paths:
      - "samples/spring-boot-3/customer-service/"
      - "samples/spring-boot-3/customer-service-client/"
      - "samples/spring-boot-4/customer-service/"
      - "samples/spring-boot-4/customer-service-client/"