coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 2%
    patch:
      default:
        enabled: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "**/target/**"
  - "**/generated/**"
  - "**/generated-sources/**"

flags:
  samples:
    paths:
      - "samples/"