services:
  customer-service:
    container_name: customer-service-sb4
    build:
      context: ..
      dockerfile: spring-boot-4/customer-service/Dockerfile
    image: customer-service-sb4:latest
    restart: on-failure
    environment:
      APP_PORT: ${APP_PORT:-8094}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
    ports:
      - "${APP_PORT:-8094}:${APP_PORT:-8094}"

  customer-service-consumer:
    container_name: customer-service-consumer-sb4
    build:
      context: ..
      dockerfile: spring-boot-4/customer-service-consumer/Dockerfile
    image: customer-service-consumer-sb4:latest
    restart: on-failure
    depends_on:
      - customer-service
    environment:
      APP_PORT: ${CONSUMER_APP_PORT:-8095}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      CUSTOMER_API_BASE_URL: "http://customer-service-sb4:8094/customer-service"
    ports:
      - "${CONSUMER_APP_PORT:-8095}:${CONSUMER_APP_PORT:-8095}"