services:
  customer-service:
    container_name: customer-service-sb3
    build:
      context: ..
      dockerfile: spring-boot-3/customer-service/Dockerfile
    image: customer-service-sb3:latest
    restart: on-failure
    environment:
      APP_PORT: ${APP_PORT:-8084}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
    ports:
      - "${APP_PORT:-8084}:${APP_PORT:-8084}"

  customer-service-consumer:
    container_name: customer-service-consumer-sb3
    build:
      context: ..
      dockerfile: spring-boot-3/customer-service-consumer/Dockerfile
    image: customer-service-consumer-sb3:latest
    restart: on-failure
    depends_on:
      - customer-service
    environment:
      APP_PORT: ${CONSUMER_APP_PORT:-8085}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      CUSTOMER_API_BASE_URL: "http://customer-service-sb3:8084/customer-service"
    ports:
      - "${CONSUMER_APP_PORT:-8085}:${CONSUMER_APP_PORT:-8085}"