title: OpenAPI Generics
description: Deterministic, generics-aware API platform (contract + server + codegen)

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

baseurl: "/openapi-generics"

# TOC davranışı (Home sayfa için kritik)
toc:
  min_level: 2
  max_level: 2

# Üst sağ link
aux_links:
  "GitHub":
    - "https://github.com/blueprint-platform/openapi-generics"

search_enabled: true